name: webscan

services:
  load_balancer:
    image: nginx:1.25.5
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80

  worker:
    build: ./WebScan-worker
    deploy:
      mode: replicated
      replicas: 3
