name: webscan

services:
  load_balancer:
    image: nginx:1.25.5
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - 80:80
      - 8000:8000
    environment:
    - NGINX_HOST=89.109.8.173
    - NGINX_PORT=80
    depends_on:
      - frontend
      - worker_1
      - worker_2
      - worker_3

  frontend:
    build: ./WebScan-frontend
    environment:
      - AUTH_TRUST_HOST=true
    env_file:
      - .env
    restart: unless-stopped

  worker_1:
    build: ./WebScan-worker
    environment:
      - PORT=1320
    env_file:
      - .env
    ports:
      - "1320:1320"
    depends_on:
      - postgres
    restart: unless-stopped

  worker_2:
    build: ./WebScan-worker
    environment:
      - PORT=1321
    env_file:
      - .env
    ports:
      - "1321:1321"
    depends_on:
      - postgres
    restart: unless-stopped

  worker_3:
    build: ./WebScan-worker
    environment:
      - PORT=1322
    env_file:
      - .env
    ports:
      - "1322:1322"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: "webscan"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    logging:
      driver: none
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d webscan"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  pgadmin:
    image: dpage/pgadmin4:8.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      GUNICORN_ACCESS_LOGFILE: /dev/null
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5000:80"
    expose:
      - 5000
    logging:
      driver: none
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

volumes:
  db-data:
  pgadmin-data:
