name: webscan

services:
  load_balancer:
    image: nginx:1.25.5
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./conf.d/:/etc/nginx/conf.d
    ports:
      - 80:80
    environment:
    - NGINX_HOST=webscan-proj.net
    - NGINX_PORT=80

  frontend:
    build: ./WebScan-frontend

  worker:
    build: ./WebScan-worker
    deploy:
      mode: replicated
      replicas: 3
